apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-consumer
  template:
    metadata:
      labels:
        app: notification-consumer
    spec:
      containers:
      - name: consumer
        image: luongmn15/notification-consumer:v1.0.0
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"